# Schema for configuration files of the Simple Dialog module.

simple_dialog.settings:
  type: mapping
  label: 'Simple Dialog settings'
  mapping:
    js_all:
      type: boolean
      label: 'Add simple dialog javscript files to all pages'
    classes:
      type: string
      label: 'Additional Classes'
    defaults:
      type: mapping
      label: 'Defaults'
      mapping:
        settings:
          type: string
          label: 'Default Dialog Settings'
        target_selector:
          type: string
          label: 'Default Target Selector'
        title:
          type: string
          label: 'Default Dialog Title'
