<?php

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
// function pw_theme_theme_suggestions_page_alter(array &$suggestions, array $variables) {

//   if ($node = \Drupal::routeMatch()->getParameter('node')) {
//     $content_type = $node->bundle();
//     $suggestions[] = 'node__'.$content_type;
//   }
// }

function pw_theme_form_alter(&$form, &$form_state, $form_id) {
    var_dump($form);
  if ($form_id == 'name_of_form') {
    $form['actions']['submit']['#value'] = 'Your button text';
  }
}