admin:
    path:   /supplier
    defaults: { _controller: BOBundle:Supplier:index }

admin_save:
    path:   /supplier/products/save
    defaults: { _controller: BOBundle:Supplier:save }

admin_products:
    path:   /supplier/products/{id}
    defaults: { _controller: BOBundle:Supplier:products }