bo:
    resource: "@BOBundle/Resources/config/routing.yml"
    prefix:   /bo

wedding:
    resource: "@WeddingBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation